name: trpc_client_generator
description: A TRPC router mapper for Dart.
version: 0.1.4
repository: https://github.com/wosherco/trpc-client-dart
issue_tracker: https://github.com/wosherco/trpc-client-dart/issues
homepage: https://github.com/wosherco/trpc-client-dart

environment:
  sdk: ^3.5.0

dependencies:
  trpc_client_annotations: ^0.1.1
  source_gen: ^1.5.0
  analyzer: ">=5.2.0 <7.0.0"
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.4
  build: ^2.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.7.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
