name: trpc_client_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  trpc_client: ^0.4.0
  trpc_client_annotations: ^0.1.1

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  trpc_client_generator: ^0.1.5
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
