name: trpc_client_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  trpc_client: ^0.3.4
  trpc_client_annotations: ^0.1.0
  trpc_client_generator: ^0.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
