name: trpc_client_annotations
description: Annotations for trpc_client_generator
version: 0.1.0
repository: https://github.com/wosherco/trpc-client-dart
issue_tracker: https://github.com/wosherco/trpc-client-dart/issues
homepage: https://github.com/wosherco/trpc-client-dart

resolution: workspace

environment:
  sdk: ^3.5.0

# dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
