// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
/// This file is generated by trpc_client_generator.

part of 'trpc.dart';

// **************************************************************************
// Generator: TRPCRoutesBuilder
// **************************************************************************

class _R$hello {
  final TRPCClient _client;
  const _R$hello(this._client);
  Future<void> mutate(HelloInput input) async {
    final response = await _client.mutate('hello', payload: input.toJson());
    final returnData = response.unwrap();
  }
}

class _R$nested_hello2 {
  final TRPCClient _client;
  const _R$nested_hello2(this._client);
  Future<void> mutate() async {
    final response = await _client.mutate('nested.hello2');
    final returnData = response.unwrap();
  }
}

class _R$nested_nestedx2_hello7 {
  final TRPCClient _client;
  const _R$nested_nestedx2_hello7(this._client);
  Future<Nested_nestedx2_hello7Output> mutate() async {
    final response = await _client.mutate('nested.nestedx2.hello7');
    final returnData = response.unwrap();
    return Nested_nestedx2_hello7Output.fromJson(returnData);
  }
}

class _RTR$Router {
  final TRPCClient _client;
  _RTR$Router(this._client);
  late final hello = _R$hello(_client);
  late final nested = _RTR$nested_Router(_client);
}

class _RTR$hello_Router {
  final TRPCClient _client;
  _RTR$hello_Router(this._client);
}

class _RTR$nested_Router {
  final TRPCClient _client;
  _RTR$nested_Router(this._client);
  late final hello2 = _R$nested_hello2(_client);
  late final nestedx2 = _RTR$nested_nestedx2_Router(_client);
}

class _RTR$nested_hello2_Router {
  final TRPCClient _client;
  _RTR$nested_hello2_Router(this._client);
}

class _RTR$nested_nestedx2_Router {
  final TRPCClient _client;
  _RTR$nested_nestedx2_Router(this._client);
  late final hello7 = _R$nested_nestedx2_hello7(_client);
}

class _RTR$nested_nestedx2_hello7_Router {
  final TRPCClient _client;
  _RTR$nested_nestedx2_hello7_Router(this._client);
}
