// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
/// This file is generated by trpc_client_generator.

part of 'trpc.dart';

// **************************************************************************
// Generator: TRPCModelsBuilder
// **************************************************************************

@freezed
class HelloInput with _$HelloInput {
  const factory HelloInput({
    required String hello,
    required Works works,
  }) = _HelloInput;

  factory HelloInput.fromJson(Map<String, dynamic> json) =>
      _$HelloInputFromJson(json);
}

@freezed
class Works with _$Works {
  const factory Works({
    required bool no,
    required bool yes,
  }) = _Works;

  factory Works.fromJson(Map<String, dynamic> json) => _$WorksFromJson(json);
}

@freezed
class NestedHello2Input with _$NestedHello2Input {
  const factory NestedHello2Input({
    required String userId,
    required String listId,
  }) = _NestedHello2Input;

  factory NestedHello2Input.fromJson(Map<String, dynamic> json) =>
      _$NestedHello2InputFromJson(json);
}

@freezed
class NestedNestedx2Hello7Output with _$NestedNestedx2Hello7Output {
  const factory NestedNestedx2Hello7Output({
    required bool hello,
  }) = _NestedNestedx2Hello7Output;

  factory NestedNestedx2Hello7Output.fromJson(Map<String, dynamic> json) =>
      _$NestedNestedx2Hello7OutputFromJson(json);
}
