/// This file is generated by trpc_generator.
/// Do not edit this file directly.

part of 'trpc.dart';

// **************************************************************************
// Generator: TRPCRoutesBuilder
// **************************************************************************

@freezed
class HelloInput with _$HelloInput {
  factory HelloInput({
    required String hello,
  }) = _HelloInput;
  factory HelloInput.fromJson(Map<String, dynamic> json) =>
      _$HelloInputFromJson(json);
}

class TrpcClient {
  Future<HelloOutput> hello(HelloInput input) async {
    // Implement the actual TRPC call here
    throw UnimplementedError();
  }
}
