import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';
import 'package:trpc_client_generator/src/router/generator.dart';
import 'package:trpc_client_generator/src/models/generator.dart';

Builder generateTRPCRoutes(BuilderOptions options) =>
    PartBuilder([TRPCRoutesBuilder()], ".router.dart",
        header: '''
/// This file is generated by trpc_client_generator.
/// Do not edit this file directly.
''',
        options: options);

Builder generateTRPCModels(BuilderOptions options) => PartBuilder(
      [TRPCModelsBuilder()],
      ".models.dart",
      header: '''
/// This file is generated by trpc_client_generator.
/// Do not edit this file directly.
''',
      options: options,
    );
