import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';
import 'package:trpc_client_generator/src/generator.dart';

Builder generateTRPCRoutes(BuilderOptions options) =>
    PartBuilder([TRPCRoutesBuilder()], ".trpc.dart",
        header: '''
/// This file is generated by trpc_generator.
/// Do not edit this file directly.
''',
        options: options);
